# .github/workflows/gh.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g vite

      # Copy all example files to dist during build
      - name: Create build script
        run: |
          echo '#!/bin/bash
          mkdir -p dist/examples
          cp -r src/examples dist/
          npm run build' > build.sh
          chmod +x build.sh

      - name: Build project
        run: ./build.sh
        env:
          VITE_APP_BASE_URL: 'https://demastery.com'
          NODE_ENV: 'production'

      # Ensure examples directory exists in dist after build
      - name: Verify build
        run: |
          if [ ! -d "dist/examples" ]; then
            echo "Examples directory missing from build"
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4